image: gitpod/workspace-postgres

tasks:
  - init: npm install
    command: exported HMR_HOST=`gp url 3000` && npm run dev
    env: DATABASE_URL: postgres://gitpod@localhost/todos

ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
